---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: ubuntu
    run_list:
      - recipe[chef-awesome-appliance-repair::default]
    attributes:
    excludes:
      - centos-6.4
  - name: centos
    run_list:
    attributes:
    excludes:
      - ubuntu-12.04
