---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[chef-awesome-appliance-repair::default]
    attributes:
    excludes: centos-6.4
  - name: redhat
    run_list:
      - recipe[chef-awesome-appliance-repair::default]
    excludes: ubuntu-12.04